name: CI/CD

on:
  push:
    branches:
      - main2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Run format
        run: npm run format:check

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: prj_j7oj25x4BGY4TOIaZN862VVdsKDX
        run: |
          curl --request POST \
            --url "https://api.vercel.com/v13/now/deployments" \
            --header "Authorization: Bearer $VERCEL_TOKEN" \
            --header "Content-Type: application/json" \
            --data '{
              "name": "production",
              "projectId": "$VERCEL_PROJECT_ID",
              "alias": "[next-family-soundboard.vercel.app]",
              "target": "production",
              "withLatestCommit": true,
              "forceNew": true,
              "gitMetadata": {
                "commitRef": "main2"
              }
            }' \
            --fail
